lang/python/details/flask/fl_login_complete/fl_login/models.py
from fl_login import db
from flask_login import UserMixin
from datetime import datetime

class User(UserMixin, db.Model):
  id = db.Column(db.Integer, primary_key=True)
  username = db.Column(db.String(15), unique=True, nullable=False)
  email = db.Column(db.String(50), unique=True, nullable=False)
  password = db.Column(db.String(80), nullable=False)
  # toString de la requete table.query.all()
  def __repr__(self):
    return f"User('{self.username}', '{self.email}'')"

lang/python/details/flask/fl_login_complete/fl_login/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import InputRequired, Length, Email

class LoginForm(FlaskForm):
  username = StringField('Username', validators = [ InputRequired()] , render_kw={'autofocus' : True, 'placeholder' : 'username' } )
  password = PasswordField('Password', validators = [ InputRequired()] , render_kw={'autofocus' : True })
  remember = BooleanField('Remerber me')
  submit_button = SubmitField('Login')

class RegisterForm(FlaskForm):
  username = StringField('Username', validators = [ InputRequired(), Length(min=4, max=15, message='Username between 4 and 15 characters') ], render_kw={'placeholder' : 'username'} )
  email = StringField('Email', validators = [ InputRequired(), Length(max=50, message='Email max 80 characters') ], render_kw={'placeholder':'email@mail.com'} )
  password = PasswordField('Password', validators = [ InputRequired(), Length(min=4, max=80, message='password between 4 and 80 characters') ], render_kw={'placeholder':'your strongest password'} )
  submit_button = SubmitField('Register')

lang/python/details/flask/fl_login_complete/fl_login/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_debugtoolbar import DebugToolbarExtension
from flask_login import LoginManager
from fl_login.config import Config
from fl_login.db import db
from fl_login.models import *


# instanciate Flask extentions
toolbar = DebugToolbarExtension()
Bootstrap = Bootstrap()
login_manager = LoginManager()
# db already instanciated and imported from db.py

# Create the app
def create_app(test_config=None):
  # Instantiate the App and config (def instance dir = ./instance)
    # Instantiate the Flask app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(Config)

    # init_app each Extension
    db.init_app(app)
    toolbar.init_app(app)
    Bootstrap.init_app(app)
    login_manager.init_app(app)
    # creation of the schema in .db file
    with app.app_context():
      # Extensions now knows which "app" to use
      # prevent error like : "No application found. Either work inside a view function or push an application context."
      # create db
      db.create_all()
      # force non_loggedinuser to go to users.login
      login_manager.login_view = 'users.login'
      
    # register the database commands
    from fl_login.main.routes import main
    from fl_login.users.routes import users
    app.register_blueprint(main)
    app.register_blueprint(users)
    
    return app

lang/python/details/flask/fl_login_complete/fl_login/main/routes.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

main = Blueprint('main', __name__ )

@main.route('/')
def index():
  return render_template('index.html')

@main.route('/dashboard')
@login_required
def dashboard():
  return render_template('dashboard.html', name=current_user.username)

lang/python/details/flask/fl_login_complete/fl_login/users/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for
from fl_login.users.forms import *
from fl_login.users.utils import *
from fl_login import db
from fl_login.models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

users = Blueprint('users', __name__ )

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(username = form.username.data).first()
    if user :
      if check_password_hash(user.password, form.password.data):
        # load user into flask_login.current_user cookie
        login_user(user, remember=form.remember.data)
        return redirect(url_for('main.dashboard'))
    flash('Invalid username or password', 'error')
  return render_template('login.html', form=form)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegisterForm()
  if form.validate_on_submit():
    hashed_password = generate_password_hash(form.password.data, method='sha256')
    user = User(username=form.username.data, email=form.email.data, password=hashed_password)
    db.session.add(user)
    db.session.commit()
    flash('User registered, now you can log you in', 'success')
    return redirect(url_for('users.login'))
  return render_template('register.html', form=form )

@users.route('/logout')
# force user to be logged in cf__init__.py Login_manager.login_view
@login_required
def logout():
  # unload user from flask_login.current_user cookie
  logout_user()
  return redirect(url_for('main.index'))

lang/python/details/flask/fl_login_complete/fl_login/templates/dashboard.html
{% extends "layout/default.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Login
{% endblock %}

{% block content %}
{{ super() }}
  <div class='container'>
    <h1>Welcome, {{ name }}</h1>
  </div>

{% endblock %}

lang/python/details/flask/fl_login_complete/fl_login/templates/index.html
{% extends "layout/default.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Home
{% endblock %}

{% block content %}
{{ super() }}
<div class='container'>
<h1>Fl Login Complete</h1>
</div>
{% endblock %}

lang/python/details/flask/fl_login_complete/fl_login/templates/layout/default.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
  {{ page_title or "Fl Login Complete" }}
{% endblock title %}

{% block navbar %}
  <nav class="navbar navbar-inverse navbar-default">
    <div class='container'>
    <div class="navbar-header">
      <a class="navbar-brand" href={{ url_for('main.index') }}>Home</a>
      {% if current_user.is_authenticated %}
      <a class="navbar-brand" href={{ url_for('main.dashboard') }}>Dashboard</a>
      <a class="navbar-brand" href={{ url_for('users.logout') }}>Logout</a>
      {% else %}
      <a class="navbar-brand" href={{ url_for('users.login') }}>Login</a>
      <a class="navbar-brand" href={{ url_for('users.register') }}>Register</a>
      {% endif %}
    </div>
    </div>
  </nav>
{% endblock navbar %}

{% block content %}

<div class='container'>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  {% if form %}
    {{ wtf.quick_form(form, button_map={'submit_button':'primary'}) }}
  {% endif %}
</div>

{% endblock content %}

lang/python/details/flask/fl_login_complete/fl_login/templates/login.html
{% extends "layout/default.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Login
{% endblock %}

{% block content %}
{{ super() }}
{% endblock %}

lang/python/details/flask/fl_login_complete/fl_login/templates/register.html
{% extends "layout/default.html" %}

{% block title %}
Register
{% endblock %}

{% block content %}
{{ super() }}
{% endblock %}