lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/models.py
from fl_sqlalchemy import db
from datetime import datetime

class User(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  username = db.Column(db.String(20), unique=True, nullable=False)
  email = db.Column(db.String(120),  nullable=False)
  password = db.Column(db.String(60), nullable=False)
  # back reference de post permettant les requete de type user.posts[1] 
  posts = db.relationship('Post', backref='author', lazy=True)
  
  # toString de la requete table.query.all()
  def __repr__(self):
    return f"User('{self.username}', '{self.email}'')"



class Post(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  title = db.Column(db.String(100), nullable=False)
  date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
  content = db.Column(db.Text, nullable=False)
  # FK
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

  # toString de la requete table.query.all()
  def __repr__(self):
    return f"Post('{self.title}', '{self.date_posted}')"

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired

class PostForm(FlaskForm):
  title = StringField('Title', validators = [ InputRequired() ] )
  content = StringField('Content', validators = [ InputRequired() ] )
  user_id = StringField('Owner username', validators = [ InputRequired() ] )
  submit_button = SubmitField('Add')

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired

class UserForm(FlaskForm):
  username = StringField('Username', validators = [ InputRequired() ] )
  password = PasswordField('Password', validators = [ InputRequired() ] )
  email = StringField('Mail', validators = [ InputRequired() ] )
  submit_button = SubmitField('Add')

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_debugtoolbar import DebugToolbarExtension
from fl_sqlalchemy.config import Config
from fl_sqlalchemy.db import db
from fl_sqlalchemy.models import *

# instanciate Flask extentions
toolbar = DebugToolbarExtension()
Bootstrap = Bootstrap()
# db already instanciated and imported from db.py

# CF README pour plus de detail sur DB

# Create the app
def create_app():
  # Instantiate the App and config (def instance dir = ./instance)
    # Instantiate the Flask app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(Config)

    db.init_app(app)
    toolbar.init_app(app)
    Bootstrap.init_app(app)

    # creation of the schema in .db file
    with app.app_context():
      # Extensions now knows which "app" to use
      # prevent error like : "No application found. Either work inside a view function or push an application context."
      db.create_all()

    # register the database commands
    from fl_sqlalchemy.main.routes import main
    from fl_sqlalchemy.posts.routes import posts
    from fl_sqlalchemy.users.routes import users
    app.register_blueprint(main)
    app.register_blueprint(posts)
    app.register_blueprint(users)

    return app

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__ )

@main.route('/')
def home():
  return render_template('index.html')

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/posts/routes.py
from flask import Blueprint, render_template, flash
from fl_sqlalchemy.posts.forms import PostForm
from fl_sqlalchemy import db
from fl_sqlalchemy.models import Post, User

posts = Blueprint('posts', __name__ )

@posts.route('/add_post', methods=('GET','POST') )
def add_post():
  form = PostForm()
  if form.validate_on_submit() :
    user_id = User.query.filter_by(username=form.user_id.data).first().id
    post = Post( title = form.title.data , user_id = user_id , content = form.content.data )
    db.session.add(post)
    db.session.commit()
    flash('Post created : ' + form.title.data, 'success')
    return render_template('index.html',page_title = 'Add Post')
  else :
    return render_template('add_post.html', page_title = 'Add Post', form = form)

@posts.route('/list_posts')
def list_posts():
  posts = Post.query.all()
  return render_template('list_posts.html', page_title = 'List posts', posts = posts )

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/users/routes.py
from flask import Blueprint, render_template, flash
from fl_sqlalchemy.users.forms import UserForm
from fl_sqlalchemy import db
from fl_sqlalchemy.models import User

users = Blueprint('users', __name__ )

@users.route('/add_user', methods=('GET','POST') )
def add_user():
  form = UserForm()
  if form.validate_on_submit() :
    user = User( username = form.username.data , password = form.password.data, email = form.email.data )
    db.session.add(user)
    db.session.commit()
    flash('Account created : ' + form.username.data, 'success')
    return render_template('index.html',page_title = 'Add User')
  else :
    return render_template('add_user.html', page_title = 'Add User', form = form)

@users.route('/list_users')
def list_users():
  users = User.query.all()
  return render_template('list_users.html', page_title = 'List Users', users = users )

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/templates/add_post.html
{% extends 'layout/default.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">

  <h1>{{ page_title }}</h1>
  <form method="POST" action="{{ url_for('posts.add_post') }}">

  {{ wtf.quick_form(form) }}



</div>
{% endblock content %}

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/templates/add_user.html
{% extends 'layout/default.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">

  <h1>{{ page_title }}</h1>
  <form method="POST" action="{{ url_for('users.add_user') }}">

  {{ wtf.quick_form(form) }}



</div>
{% endblock content %}

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/templates/index.html
{% extends 'layout/default.html' %}

{% block content %}
<div class="container">

  <h1>Hello, Fl SQLAlchemy</h1>

</div>
<div class="col-md-8">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{category}}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
</div>
  
{% endblock content %}

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/templates/layout/default.html
{% extends 'bootstrap/base.html' %}

{% block title %}
  {{ page_title or "Fl SQLAlchemy" }}
{% endblock title %}

{% block navbar %}
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <a class="navbar-brand" href={{ url_for('main.home') }} >Home</a>
    <a class="navbar-brand" href={{ url_for('users.add_user') }} >Add User</a>
    <a class="navbar-brand" href={{ url_for('users.list_users') }} >List Users</a>
    <a class="navbar-brand" href={{ url_for('posts.add_post') }} >Add Post</a>
    <a class="navbar-brand" href={{ url_for('posts.list_posts') }} >List Posts</a>
  </div>
</nav>
{% endblock navbar %}

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/templates/list_posts.html
{% extends 'layout/default.html' %}

{% block content %}
<div class="container">

  <h1>Hello, Fl SQLAlchemy</h1>
  
    {% for post in posts %}
    <h2>{{ post.title }}</h2>
    <p class="lead"><i class="fa fa-user"></i> by {{ post.author.username }} </p>
    <p><i class="fa fa-calendar"></i> Posted on {{ post.date_posted }}</p>
    <p> {{ post.content }}</p>
    {% endfor %}

</div>
{% endblock content %}

lang/python/details/flask/fl_sqlalchemy/fl_sqlalchemy/templates/list_users.html
{% extends 'layout/default.html' %}

{% block content %}
<div class="container">

  <h1>Hello, Fl SQLAlchemy</h1>

  <ul class="list-group">
    {% for user in users %}
    <li class="list-group-item">{{ user.username }} : {{ user.email }}</li>
    {% endfor %}
  </ul>
</div>
{% endblock content %}